### ISSUE TITLE
Moodle installation problem

### ISSUE THREAD

**Issue by rr83019** [docker-scripts/moodle#5]
I get these errors when i run `ds make` or `ds config`:

`moodle1-example-org

--> Running script '/usr/lib/ds/scripts/ubuntu-fixes.sh'
+ sed -i /etc/logrotate.d/rsyslog -e 's/invoke-rc.d rsyslog rotate/invoke-rc.d --quiet rsyslog rotate/'

--> Running script '/usr/lib/ds/scripts/set_prompt.sh'
+ source /host/settings.sh
++ APP=moodle
++ MOODLE_BRANCH=MOODLE_34_STABLE
++ IMAGE=dockerscripts/moodle
++ CONTAINER=moodle1-example-org
++ DOMAIN=moodle1.example.org
++ DBNAME=moodle
++ DBUSER=moodle
++ DBPASS=moodle
++ GMAIL_ADDRESS=
++ GMAIL_PASSWD=
++ SITE_LANG=en
++ SITE_FULLNAME=
++ SITE_SHORTNAME=
++ ADMIN_USER=admin
++ ADMIN_PASS=
++ ADMIN_EMAIL=
++ GOOGLE_CLIENT_ID=
++ GOOGLE_CLIENT_SECRET=
++ PLUGINS='
    mod_bigbluebuttonbn
    mod_recordingsbn
    mod_offlinequiz
    qbehaviour_adaptive_adapted_for_coderunner
    qtype_coderunner
    atto_mathslate
    tinymce_mathslate
    mod_webrtcexperiments
'
++ OFFLINEQUIZ_LOGOURL=
+ echo moodle1-example-org
+ sed -i /root/.bashrc -e '/^#force_color_prompt=/c force_color_prompt=yes'
+ PS1='\\n\\[\\033[01;32m\\]${debian_chroot:+$debian_chroot }\\[\\033[00m\\]\\u@\\h\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w\\[\\e[32m\\]\\n==> \\$ \\[\\033[00m\\]'
+ sed -i /root/.bashrc -e '/^if \[ "$color_prompt" = yes \]/,+2 s/PS1=.*/PS1='\''\\n\\[\\033[01;32m\\]${debian_chroot:+$debian_chroot }\\[\\033[00m\\]\\u@\\h\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w\\[\\e[32m\\]\\n==> \\$ \\[\\033[00m\\]'\''/'

--> Running script '/usr/lib/ds/scripts/ssmtp.sh'
+ source /host/settings.sh
++ APP=moodle
++ MOODLE_BRANCH=MOODLE_34_STABLE
++ IMAGE=dockerscripts/moodle
++ CONTAINER=moodle1-example-org
++ DOMAIN=moodle1.example.org
++ DBNAME=moodle
++ DBUSER=moodle
++ DBPASS=moodle
++ GMAIL_ADDRESS=
++ GMAIL_PASSWD=
++ SITE_LANG=en
++ SITE_FULLNAME=
++ SITE_SHORTNAME=
++ ADMIN_USER=admin
++ ADMIN_PASS=
++ ADMIN_EMAIL=
++ GOOGLE_CLIENT_ID=
++ GOOGLE_CLIENT_SECRET=
++ PLUGINS='
    mod_bigbluebuttonbn
    mod_recordingsbn
    mod_offlinequiz
    qbehaviour_adaptive_adapted_for_coderunner
    qtype_coderunner
    atto_mathslate
    tinymce_mathslate
    mod_webrtcexperiments
'
++ OFFLINEQUIZ_LOGOURL=
+ [[ -z '' ]]
+ exit 0

--> Running script '/usr/lib/ds/scripts/mariadb.sh'
++ mcookie
++ head -c 16
+ passwd=f297ff4a3be565ef
+ mysql --defaults-file=/etc/mysql/debian.cnf -B -e 'SET PASSWORD FOR '\''debian-sys-maint'\''@'\''localhost'\'' = PASSWORD('\''f297ff4a3be565ef'\'');'
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
++ mcookie
++ head -c 16
+ passwd=1b7c156e6701adda
+ query='update mysql.user set authentication_string=PASSWORD("1b7c156e6701adda") where User="root"; flush privileges;'
+ debian_cnf=/etc/mysql/debian.cnf
+ mysql --defaults-file=/etc/mysql/debian.cnf -B -e 'update mysql.user set authentication_string=PASSWORD("1b7c156e6701adda") where User="root"; flush privileges;'
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

--> Running script '/usr/lib/ds/scripts/apache2.sh'
+ source /host/settings.sh
++ APP=moodle
++ MOODLE_BRANCH=MOODLE_34_STABLE
++ IMAGE=dockerscripts/moodle
++ CONTAINER=moodle1-example-org
++ DOMAIN=moodle1.example.org
++ DBNAME=moodle
++ DBUSER=moodle
++ DBPASS=moodle
++ GMAIL_ADDRESS=
++ GMAIL_PASSWD=
++ SITE_LANG=en
++ SITE_FULLNAME=
++ SITE_SHORTNAME=
++ ADMIN_USER=admin
++ ADMIN_PASS=
++ ADMIN_EMAIL=
++ GOOGLE_CLIENT_ID=
++ GOOGLE_CLIENT_SECRET=
++ PLUGINS='
    mod_bigbluebuttonbn
    mod_recordingsbn
    mod_offlinequiz
    qbehaviour_adaptive_adapted_for_coderunner
    qtype_coderunner
    atto_mathslate
    tinymce_mathslate
    mod_webrtcexperiments
'
++ OFFLINEQUIZ_LOGOURL=
+ DOMAIN=moodle1.example.org
+ mkdir -p /var/log/apache2
+ mkdir -p /var/www/default
+ cat
+ ln /etc/apache2/sites-available/default.conf /etc/apache2/sites-available/moodle1.example.org.conf
+ a2enmod ssl
Considering dependency setenvif for ssl:
Module setenvif already enabled
Considering dependency mime for ssl:
Module mime already enabled
Considering dependency socache_shmcb for ssl:
Enabling module socache_shmcb.
Enabling module ssl.
See /usr/share/doc/apache2/README.Debian.gz on how to configure SSL and create self-signed certificates.
To activate the new configuration, you need to run:
  service apache2 restart
+ a2ensite default
Enabling site default.
To activate the new configuration, you need to run:
  service apache2 reload
+ a2dissite 000-default
Site 000-default disabled.
To activate the new configuration, you need to run:
  service apache2 reload
+ service apache2 restart
+ cat
+ chmod +x /usr/local/sbin/apachemonitor.sh
+ mkdir -p /etc/cron.d/
+ cat
+ chmod +x /etc/cron.d/apachemonitor

--> Running script '/opt/docker-scripts/moodle/scripts/cfg/01_mount_tmp_on_ram.sh'
+ sed -i /etc/fstab -e '/appended by installation scripts/,$ d'
+ cat
+ mount -a

--> Running script '/opt/docker-scripts/moodle/scripts/cfg/02_fix_apache2_config.sh'
+ sed -i /etc/apache2/sites-available/default.conf -e s#/var/www/default#/var/www/moodle#g
+ service apache2 reload

--> Running script '/opt/docker-scripts/moodle/scripts/cfg/03_mariadb_config.sh'
+ cat
+ service mysql restart
Job for mariadb.service failed because the control process exited with error code. See "systemctl status mariadb.service" and "journalctl -xe" for details.

--> Running script '/opt/docker-scripts/moodle/scripts/cfg/04_create_db.sh'
+ source /host/settings.sh
++ APP=moodle
++ MOODLE_BRANCH=MOODLE_34_STABLE
++ IMAGE=dockerscripts/moodle
++ CONTAINER=moodle1-example-org
++ DOMAIN=moodle1.example.org
++ DBNAME=moodle
++ DBUSER=moodle
++ DBPASS=moodle
++ GMAIL_ADDRESS=
++ GMAIL_PASSWD=
++ SITE_LANG=en
++ SITE_FULLNAME=
++ SITE_SHORTNAME=
++ ADMIN_USER=admin
++ ADMIN_PASS=
++ ADMIN_EMAIL=
++ GOOGLE_CLIENT_ID=
++ GOOGLE_CLIENT_SECRET=
++ PLUGINS='
    mod_bigbluebuttonbn
    mod_recordingsbn
    mod_offlinequiz
    qbehaviour_adaptive_adapted_for_coderunner
    qtype_coderunner
    atto_mathslate
    tinymce_mathslate
    mod_webrtcexperiments
'
++ OFFLINEQUIZ_LOGOURL=
+ mysql -e '
    DROP DATABASE IF EXISTS moodle;
    CREATE DATABASE moodle;
    GRANT ALL ON moodle.* TO moodle@localhost IDENTIFIED BY '\''moodle'\'';
'
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

--> Running script '/opt/docker-scripts/moodle/scripts/cfg/05_moodle_install.sh'
+ source /host/settings.sh
++ APP=moodle
++ MOODLE_BRANCH=MOODLE_34_STABLE
++ IMAGE=dockerscripts/moodle
++ CONTAINER=moodle1-example-org
++ DOMAIN=moodle1.example.org
++ DBNAME=moodle
++ DBUSER=moodle
++ DBPASS=moodle
++ GMAIL_ADDRESS=
++ GMAIL_PASSWD=
++ SITE_LANG=en
++ SITE_FULLNAME=
++ SITE_SHORTNAME=
++ ADMIN_USER=admin
++ ADMIN_PASS=
++ ADMIN_EMAIL=
++ GOOGLE_CLIENT_ID=
++ GOOGLE_CLIENT_SECRET=
++ PLUGINS='
    mod_bigbluebuttonbn
    mod_recordingsbn
    mod_offlinequiz
    qbehaviour_adaptive_adapted_for_coderunner
    qtype_coderunner
    atto_mathslate
    tinymce_mathslate
    mod_webrtcexperiments
'
++ OFFLINEQUIZ_LOGOURL=
+ mkdir -p /host/data
+ chown -R www-data /host/data
+ chmod -R 777 /host/data
+ [[ ! -f /var/www/moodle/config.php ]]
+ rm -rf /var/www/moodle
+ cp -a /usr/local/src/moodle /var/www/
+ cd /var/www/moodle/
+ git pull
Already up-to-date.
+ git checkout MOODLE_34_STABLE
Branch MOODLE_34_STABLE set up to track remote branch MOODLE_34_STABLE from origin.
Switched to a new branch 'MOODLE_34_STABLE'
+ cat
+ chown -R www-data: /var/www
+ [[ -f /var/www/moodle/config.php ]]
+ sudo --user=www-data php admin/cli/install.php --non-interactive --agree-license --wwwroot=https://moodle1.example.org --dataroot=/host/data --dbtype=mariadb --dbname=moodle --dbuser=moodle --dbpass=moodle --lang=en --fullname= --shortname= --adminuser=admin --adminpass= --adminemail=
                                 .-..-.       
   _____                         | || |       
  /____/-.---_  .---.  .---.  .-.| || | .---. 
  | |  _   _  |/  _  \/  _  \/  _  || |/  __ \
  * | | | | | || |_| || |_| || |_| || || |___/
    |_| |_| |_|\_____/\_____/\_____||_|\_____)

Moodle 3.4.1+ (Build: 20180308) command line installation program
PHP Warning:  mysqli::__construct(): (HY000/2002): No such file or directory in /var/www/moodle/lib/dml/mysqli_native_moodle_database.php on line 79
We could not connect to the database you specified. Please check your database settings.

--> Running script '/opt/docker-scripts/moodle/scripts/cfg/06_moodle_config.sh'
+ source /host/settings.sh
++ APP=moodle
++ MOODLE_BRANCH=MOODLE_34_STABLE
++ IMAGE=dockerscripts/moodle
++ CONTAINER=moodle1-example-org
++ DOMAIN=moodle1.example.org
++ DBNAME=moodle
++ DBUSER=moodle
++ DBPASS=moodle
++ GMAIL_ADDRESS=
++ GMAIL_PASSWD=
++ SITE_LANG=en
++ SITE_FULLNAME=
++ SITE_SHORTNAME=
++ ADMIN_USER=admin
++ ADMIN_PASS=
++ ADMIN_EMAIL=
++ GOOGLE_CLIENT_ID=
++ GOOGLE_CLIENT_SECRET=
++ PLUGINS='
    mod_bigbluebuttonbn
    mod_recordingsbn
    mod_offlinequiz
    qbehaviour_adaptive_adapted_for_coderunner
    qtype_coderunner
    atto_mathslate
    tinymce_mathslate
    mod_webrtcexperiments
'
++ OFFLINEQUIZ_LOGOURL=
+ mysql --database=moodle -B -e 'UPDATE mdl_user
           SET firstname='\'''\'', lastname='\''Admin'\''
           WHERE username='\''admin'\'''
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
+ sudo --user=www-data --set-home moosh --no-user-check config-set theme more
Could not find Moodle installation!
+ sudo --user=www-data --set-home moosh --no-user-check config-set registerauth email
Could not find Moodle installation!
+ sudo --user=www-data --set-home moosh --no-user-check config-set smtphosts smtp.gmail.com:465
Could not find Moodle installation!
+ sudo --user=www-data --set-home moosh --no-user-check config-set smtpsecure ssl
Could not find Moodle installation!
+ sudo --user=www-data --set-home moosh --no-user-check config-set smtpauthtype LOGIN
Could not find Moodle installation!
+ sudo --user=www-data --set-home moosh --no-user-check config-set smtpuser
Could not find Moodle installation!
+ sudo --user=www-data --set-home moosh --no-user-check config-set smtppass ''
Could not find Moodle installation!
+ sudo --user=www-data --set-home moosh --no-user-check plugin-list

--> Running script '/opt/docker-scripts/moodle/scripts/cfg/07_setup_cron.sh'
+ echo '* * * * * www-data /usr/bin/php /var/www/moodle/admin/cli/cron.php >> /var/log/cron.log 2>&1'
+ touch /var/log/cron.log
+ chown www-data /var/log/cron.log

--> Running script '/opt/docker-scripts/moodle/scripts/cfg/08_setup_oauth2_google.sh'
+ sudo --user=www-data --set-home moosh --no-user-check auth-manage enable oauth2
Could not find Moodle installation!
+ sudo --user=www-data --set-home moosh --no-user-check auth-manage up oauth2
Could not find Moodle installation!
+ source /host/settings.sh
++ APP=moodle
++ MOODLE_BRANCH=MOODLE_34_STABLE
++ IMAGE=dockerscripts/moodle
++ CONTAINER=moodle1-example-org
++ DOMAIN=moodle1.example.org
++ DBNAME=moodle
++ DBUSER=moodle
++ DBPASS=moodle
++ GMAIL_ADDRESS=
++ GMAIL_PASSWD=
++ SITE_LANG=en
++ SITE_FULLNAME=
++ SITE_SHORTNAME=
++ ADMIN_USER=admin
++ ADMIN_PASS=
++ ADMIN_EMAIL=
++ GOOGLE_CLIENT_ID=
++ GOOGLE_CLIENT_SECRET=
++ PLUGINS='
    mod_bigbluebuttonbn
    mod_recordingsbn
    mod_offlinequiz
    qbehaviour_adaptive_adapted_for_coderunner
    qtype_coderunner
    atto_mathslate
    tinymce_mathslate
    mod_webrtcexperiments
'
++ OFFLINEQUIZ_LOGOURL=
+ [[ -n '' ]]
+ exit

--> Running script '/opt/docker-scripts/moodle/scripts/cfg/09_bash_aliases.sh'
+ cat

--> Running script '/opt/docker-scripts/moodle/scripts/install-plugins.sh'
Could not find Moodle installation!
Could not find Moodle installation!
Could not find Moodle installation!
Plugin 'qbehaviour_adaptive_adapted_for_coderunner' does not support yet MOODLE_34_STABLE.
If you know what you are doing, you can install it anyway
manually with the command:
    ds exec sh -c '$moosh plugin-install -d -f qbehaviour_adaptive_adapted_for_coderunner 2017052600'

Could not find Moodle installation!
Could not find Moodle installation!
Could not find Moodle installation!
Plugin 'mod_webrtcexperiments' does not support yet MOODLE_34_STABLE.
If you know what you are doing, you can install it anyway
manually with the command:
    ds exec sh -c '$moosh plugin-install -d -f mod_webrtcexperiments '

PHP Warning:  require(/var/www/moodle/admin/cli/../../config.php): failed to open stream: No such file or directory in /var/www/moodle/admin/cli/upgrade.php on line 41
PHP Fatal error:  require(): Failed opening required '/var/www/moodle/admin/cli/../../config.php' (include_path='.:/usr/share/php') in /var/www/moodle/admin/cli/upgrade.php on line 41
PHP Warning:  require(/var/www/moodle/admin/cli/../../config.php): failed to open stream: No such file or directory in /var/www/moodle/admin/cli/purge_caches.php on line 28
PHP Fatal error:  require(): Failed opening required '/var/www/moodle/admin/cli/../../config.php' (include_path='.:/usr/share/php') in /var/www/moodle/admin/cli/purge_caches.php on line 28

--> Running script '/opt/docker-scripts/moodle/scripts/cfg/plugin/offlinequiz.sh'
+ sudo --user=www-data --set-home moosh --no-user-check config-set shufflequestions 1 offlinequiz
Could not find Moodle installation!
+ sudo --user=www-data --set-home moosh --no-user-check config-set shuffleanswers 1 offlinequiz
Could not find Moodle installation!
+ source /host/settings.sh
++ APP=moodle
++ MOODLE_BRANCH=MOODLE_34_STABLE
++ IMAGE=dockerscripts/moodle
++ CONTAINER=moodle1-example-org
++ DOMAIN=moodle1.example.org
++ DBNAME=moodle
++ DBUSER=moodle
++ DBPASS=moodle
++ GMAIL_ADDRESS=
++ GMAIL_PASSWD=
++ SITE_LANG=en
++ SITE_FULLNAME=
++ SITE_SHORTNAME=
++ ADMIN_USER=admin
++ ADMIN_PASS=
++ ADMIN_EMAIL=
++ GOOGLE_CLIENT_ID=
++ GOOGLE_CLIENT_SECRET=
++ PLUGINS='
    mod_bigbluebuttonbn
    mod_recordingsbn
    mod_offlinequiz
    qbehaviour_adaptive_adapted_for_coderunner
    qtype_coderunner
    atto_mathslate
    tinymce_mathslate
    mod_webrtcexperiments
'
++ OFFLINEQUIZ_LOGOURL=
+ sudo --user=www-data --set-home moosh --no-user-check config-set logourl '' offlinequiz
Could not find Moodle installation!
PHP Warning:  require(/var/www/moodle/admin/cli/../../config.php): failed to open stream: No such file or directory in /var/www/moodle/admin/cli/purge_caches.php on line 28
PHP Fatal error:  require(): Failed opening required '/var/www/moodle/admin/cli/../../config.php' (include_path='.:/usr/share/php') in /var/www/moodle/admin/cli/purge_caches.php on line 28
chown: cannot access '/host/data/localcache/': No such file or directory
moodle1-example-org
`

**Comment by dashohoxha** [comment]
1. These are log messages. Where are the errors?
2. If you want to share a log file, it is better to put on pastebin or on gist, and put just a link on the issue.

**Comment by dashohoxha** [comment]
I am closing this issue, so that you can open another one, about specific errors that you get, and with a specific title/subject.
